#pragma once

#define UI_STR_INICIAR              "Iniciar"
#define UI_STR_PARAR                "Parar"
#define UI_STR_PAGA_QR              "PAGA CON QR"
#define UI_STR_QR_CARD              "Aceptamos Mercado Pago y todas las billeteras virtuales con interoperabilidad QR."
#define UI_STR_COLOCA_TERMO         "COLOCA EL TERMO"
#define UI_STR_COLOCA_CARD          "No vaciar el termo en rejilla."
#define UI_STR_CARGAR_TERMO         "CARGAR TERMO"
#define UI_STR_ESTADO_ESPERA        "ESTADO: ESPERA"
#define UI_STR_ESTADO_CARGANDO      "ESTADO: CARGANDO"
#define UI_STR_TEMPERATURA          "TEMPERATURA"
#define UI_STR_LITROS_FMT           "%.1f litros"
#define UI_STR_TEMP_FMT             "%u°C"
#define UI_STR_TEMP_INVALID         "—°C"
#define UI_STR_FINISH               "LISTO EL MATE"
#define UI_STR_ERROR_PAGO           "ERROR EN EL PAGO"
#define UI_STR_ERROR_PAGO_CARD      "Reintenta con otro medio de pago"
#define UI_STR_ERROR_WIFI           "WI-FI DESCONECTADO"
#define UI_STR_ERROR_AGUA           "AGUA DESCONECTADA"
#define UI_STR_ERROR_BANDEJA        "BANDEJA GOTEO LLENA"
#define UI_STR_ERROR_PROVIDER       "Consulta al proveedor"
#define UI_STR_LOADING              "..."
